services:
  - type: web
    name: jservice-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.3
      - key: DATABASE_URL
        fromDatabase:
          name: jservice-db
          property: connectionString

databases:
  - name: jservice-db
    databaseName: jservice
    plan: free
