services:
  - type: web
    name: jservice-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
