services:
  - type: web
    name: jservice-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python db_setup.py
    startCommand: python api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: jservice-db
          property: connectionString

databases:
  - name: jservice-db
    plan: free
